import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Use — Verum Frontier",
};

const S = {
  h2: { color: "#c8941a", letterSpacing: "0.15em", fontSize: 12, textTransform: "uppercase" as const, margin: "28px 0 10px" },
  p:  { color: "rgba(255,255,255,0.7)", fontSize: 13, lineHeight: 1.9, marginBottom: 12 },
};

export default function Terms() {
  return (
    <main className="min-h-screen bg-black font-mono" style={{ padding: "48px 24px" }}>
      <div style={{ maxWidth: 720, margin: "0 auto" }}>
        <Link href="/" style={{ fontSize: 9, letterSpacing: "0.25em", color: "rgba(255,255,255,0.4)" }}>
          ← VERUM FRONTIER
        </Link>
        <h1 style={{ color: "#fff", fontSize: 18, letterSpacing: "0.2em", margin: "18px 0 4px", textTransform: "uppercase" }}>
          Terms of Use
        </h1>
        <p style={{ fontSize: 9, color: "rgba(255,255,255,0.35)", letterSpacing: "0.1em" }}>
          PLAIN-LANGUAGE TERMS · EFFECTIVE JULY 2026 · PAID CREDITS ARE LIVE; THESE TERMS GOVERN THEM
        </p>

        <h2 style={S.h2}>What this is</h2>
        <p style={S.p}>
          Verum Frontier (rabbitholeai.ai) is a research preview by Rabbit Hole AI
          (Jeremiah Dawson). The LIVE GATE routes your queries to third-party AI models
          and returns their answers together with a cost receipt and a cryptographic
          seal. The SIM DEMO mode is a simulated concept visualization and is labeled
          as such.
        </p>

        <h2 style={S.h2}>Free tier</h2>
        <p style={S.p}>
          You get 5 live queries per day at no charge, with answers capped at 1,024
          tokens. Limits may change.
        </p>

        <h2 style={S.h2}>Prepaid credits</h2>
        <p style={S.p}>
          Credit packs ($5 / $10 / $25) are sold through Stripe&apos;s hosted checkout —
          we never see your card details. Each answer debits its exact cost-plus
          total from your balance, shown on the receipt before and after. Credits
          never expire. Purchases are live and charge your card for real. If the
          gate is ever running against a test payment account, every purchase
          control is labeled TEST MODE and no real money moves — absent that
          label, the charge is real.
        </p>
        <p style={S.p}>
          Your wallet credentials live only in your browser — we hold balances
          against an anonymous wallet id, with no account and no identity attached.
          If you lose the device or clear browser storage, email support with your
          Stripe receipt and we will restore your unused balance to a new wallet.
        </p>

        <h2 style={S.h2}>Refunds</h2>
        <p style={S.p}>
          Your unused credit balance is refundable on request, no questions asked.
          Email <a href="mailto:jtdawson015@gmail.com" style={{ color: "#c8941a" }}>jtdawson015@gmail.com</a> with
          your Stripe receipt and we&apos;ll process it promptly.
        </p>

        <h2 style={S.h2}>Third-party models</h2>
        <p style={S.p}>
          Answers are generated by models served by Groq, Inc., Google, Anthropic,
          OpenAI, and xAI — whichever one you pick in the model row. Your query text
          is sent to that provider to produce the answer and is handled under their
          terms, along with any document you attach and any sealed memories the gate
          recalls for that turn. With GROUND IT on, your query is also used to run
          web searches, either by that provider&apos;s own search tool or through
          Google Search. Model outputs can be wrong, biased, or incomplete — the
          gate shows you receipts and seals, it does not make models truthful. Do not
          rely on outputs as professional advice.
        </p>

        <h2 style={S.h2}>Acceptable use</h2>
        <p style={S.p}>
          Don&apos;t use the gate to attempt illegal activity, to attack the service or its
          providers, or to circumvent rate limits. We may block abusive traffic.
        </p>

        <h2 style={S.h2}>No warranty</h2>
        <p style={S.p}>
          The service is provided as-is, without warranties of any kind, and may change
          or go offline at any time. To the maximum extent permitted by law, Rabbit
          Hole AI is not liable for damages arising from use of this preview.
        </p>

        <h2 style={S.h2}>Contact</h2>
        <p style={S.p}>
          Rabbit Hole AI — Jeremiah Dawson ·{" "}
          <a href="mailto:jtdawson015@gmail.com" style={{ color: "#c8941a" }}>jtdawson015@gmail.com</a>.
          See also the <Link href="/privacy" style={{ color: "#c8941a" }}>Privacy Note</Link>.
        </p>
      </div>
    </main>
  );
}
