import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Use — Verum Frontier",
};

const S = {
  h2: { color: "#c8941a", letterSpacing: "0.15em", fontSize: 12, textTransform: "uppercase" as const, margin: "28px 0 10px" },
  p:  { color: "rgba(255,255,255,0.7)", fontSize: 13, lineHeight: 1.9, marginBottom: 12 },
};

export default function Terms() {
  return (
    <main className="min-h-screen bg-black font-mono" style={{ padding: "48px 24px" }}>
      <div style={{ maxWidth: 720, margin: "0 auto" }}>
        <Link href="/" style={{ fontSize: 9, letterSpacing: "0.25em", color: "rgba(255,255,255,0.4)" }}>
          ← VERUM FRONTIER
        </Link>
        <h1 style={{ color: "#fff", fontSize: 18, letterSpacing: "0.2em", margin: "18px 0 4px", textTransform: "uppercase" }}>
          Terms of Use
        </h1>
        <p style={{ fontSize: 9, color: "rgba(255,255,255,0.35)", letterSpacing: "0.1em" }}>
          PLAIN-LANGUAGE TERMS · EFFECTIVE JULY 2026 · WILL BE FORMALIZED BEFORE ANY PAID LAUNCH
        </p>

        <h2 style={S.h2}>What this is</h2>
        <p style={S.p}>
          Verum Frontier (rabbitholeai.ai) is a research preview by Rabbit Hole AI
          (Jeremiah Dawson). The LIVE GATE routes your queries to third-party AI models
          and returns their answers together with a cost receipt and a cryptographic
          seal. The SIM DEMO mode is a simulated concept visualization and is labeled
          as such.
        </p>

        <h2 style={S.h2}>Free tier</h2>
        <p style={S.p}>
          You get 5 live queries per day at no charge, with answers capped at 1,024
          tokens. Limits may change. There is currently nothing to buy on this site;
          when paid credits launch they will come with their own pricing, refund, and
          billing terms shown before any payment.
        </p>

        <h2 style={S.h2}>Third-party models</h2>
        <p style={S.p}>
          Answers are generated by models served by Groq, Inc. and Google. Your query
          text is sent to the selected provider to produce the answer and is handled
          under their terms. Model outputs can be wrong, biased, or incomplete — the
          gate shows you receipts and seals, it does not make models truthful. Do not
          rely on outputs as professional advice.
        </p>

        <h2 style={S.h2}>Acceptable use</h2>
        <p style={S.p}>
          Don&apos;t use the gate to attempt illegal activity, to attack the service or its
          providers, or to circumvent rate limits. We may block abusive traffic.
        </p>

        <h2 style={S.h2}>No warranty</h2>
        <p style={S.p}>
          The service is provided as-is, without warranties of any kind, and may change
          or go offline at any time. To the maximum extent permitted by law, Rabbit
          Hole AI is not liable for damages arising from use of this preview.
        </p>

        <h2 style={S.h2}>Contact</h2>
        <p style={S.p}>
          Rabbit Hole AI — Jeremiah Dawson, via LinkedIn. See also the{" "}
          <Link href="/privacy" style={{ color: "#c8941a" }}>Privacy Note</Link>.
        </p>
      </div>
    </main>
  );
}
