// Token usage from the OpenAI-shaped APIs — OpenAI and xAI, Chat Completions
// and Responses. Pure functions, so tests pin the math without a network call.
//
// The receipt bills Usage.outputTokens at the output rate, so it must hold every
// generated token the provider bills — visible answer AND reasoning — counted
// exactly once. The two providers use the same field names with different
// meanings (pinned from each provider's own docs, 2026-09-27):
//
//   OpenAI — output_tokens / completion_tokens ALREADY INCLUDE reasoning:
//     "Reported output token usage includes all tokens generated by the model,
//      not only the text visible in a response."
//       — developers.openai.com/api/docs/guides/token-counting
//     Documented example: input 75, output 1186 (reasoning 1024), total 1261
//     = 75 + 1186. (developers.openai.com/api/docs/guides/reasoning)
//   xAI — output_tokens / completion_tokens are the VISIBLE answer only;
//     reasoning is reported beside them and billed at "Full completion token
//     price" (docs.x.ai/developers/advanced-api-usage/prompt-caching/usage-and-pricing).
//     Documented example: input 32, output 9, reasoning 110, total 151
//     = 32 + 9 + 110. (docs.x.ai/developers/rest-api-reference/inference/responses)
//
// Reading completion_tokens alone under-counted every Grok receipt — 7× on the
// documented example. Rather than branch on the provider name, the usage object
// shows which convention it follows: reasoning is added only when total_tokens
// accounts for it separately, or when it is larger than the output count (so it
// cannot be a part of it). OpenAI's reasoning is always a subset of its output
// and its total is input + output, so it never qualifies and is never
// double-counted. With neither proof, the reported output stands.
//
// Cache WRITES are read for OpenAI only, and that one does branch on the
// provider. GPT-5.6 caches by default and bills what it writes at 1.25× input
// (pinned from OpenAI's own docs, 2026-09-27):
//   "For GPT-5.6 and later, cache writes cost 1.25× the standard, uncached
//    input-token rate." — developers.openai.com/api/docs/guides/prompt-caching
//   prompt_cache_options.mode "Defaults to `implicit`. With `implicit`, OpenAI
//    creates one implicit breakpoint" — on both /v1/responses and
//    /v1/chat/completions (developers.openai.com/api/reference/resources/
//    responses/methods/create and .../resources/chat)
// Reported as input_tokens_details.cache_write_tokens (Responses) and
// prompt_tokens_details.cache_write_tokens (Chat Completions). Those tokens are
// INSIDE input_tokens and disjoint from cached_tokens — the guide's own cost
// formula is "ordinaryInputTokens = inputTokens - cachedTokens - cacheWriteTokens".
// Unread, they were receipted at the plain input rate: 25% under on each one.
// xAI documents no cache-write field or rate, so a same-named field showing up
// there has no pinned price to bill at; it is ignored until one is pinned.
import type { Provider, Usage } from "./pricing";

export interface OpenAIShapeUsage {
  prompt_tokens?: unknown;
  completion_tokens?: unknown;
  input_tokens?: unknown;
  output_tokens?: unknown;
  total_tokens?: unknown;
  prompt_tokens_details?: { cached_tokens?: unknown; cache_write_tokens?: unknown } | null;
  input_tokens_details?: { cached_tokens?: unknown; cache_write_tokens?: unknown } | null;
  completion_tokens_details?: { reasoning_tokens?: unknown } | null;
  output_tokens_details?: { reasoning_tokens?: unknown } | null;
}

type Raw = OpenAIShapeUsage | null | undefined;

const count = (v: unknown): number | null =>
  typeof v === "number" && Number.isFinite(v) && v >= 0 ? v : null;

// First field the provider actually reported, else 0.
const first = (...vs: unknown[]): number => {
  for (const v of vs) {
    const n = count(v);
    if (n !== null) return n;
  }
  return 0;
};

export function billedOutputTokens(input: number, output: number, reasoning: number, total: number | null): number {
  if (reasoning <= 0) return output;
  const reportedSeparately = (total !== null && total >= input + output + reasoning) || reasoning > output;
  return reportedSeparately ? output + reasoning : output;
}

function build(input: number, output: number, reasoning: number, cached: number, written: number, total: number | null): Usage {
  const usage: Usage = {
    inputTokens: input,
    outputTokens: billedOutputTokens(input, output, reasoning, total),
    cachedInputTokens: cached,
  };
  // Shown on the receipt as the part of outputTokens that was reasoning. Absent
  // when none was reported, so those receipts keep the shape they had.
  if (reasoning > 0) usage.reasoningTokens = reasoning;
  // Same rule for cache writes: present only when some were billed.
  if (written > 0) usage.cacheWriteTokens = written;
  return usage;
}

// Chat Completions: prompt_tokens INCLUDES cached and cache-written tokens.
export function chatCompletionsUsage(u: Raw, provider: Provider): Usage {
  return build(
    first(u?.prompt_tokens),
    first(u?.completion_tokens),
    first(u?.completion_tokens_details?.reasoning_tokens),
    first(u?.prompt_tokens_details?.cached_tokens),
    provider === "openai" ? first(u?.prompt_tokens_details?.cache_write_tokens) : 0,
    count(u?.total_tokens),
  );
}

// Responses API: input_tokens INCLUDES cached and cache-written tokens; those
// portions are under input_tokens_details (OpenAI) or prompt_tokens_details (xAI
// compat). The chat-shaped names are read as a fallback — xAI documents them on
// GET /v1/responses/{id} — so a shape change can't zero a receipt.
export function responsesUsage(u: Raw, provider: Provider): Usage {
  return build(
    first(u?.input_tokens, u?.prompt_tokens),
    first(u?.output_tokens, u?.completion_tokens),
    first(u?.output_tokens_details?.reasoning_tokens, u?.completion_tokens_details?.reasoning_tokens),
    first(u?.input_tokens_details?.cached_tokens, u?.prompt_tokens_details?.cached_tokens),
    provider === "openai"
      ? first(u?.input_tokens_details?.cache_write_tokens, u?.prompt_tokens_details?.cache_write_tokens)
      : 0,
    count(u?.total_tokens),
  );
}
